"""increase_error_description_length

Revision ID: 7da60ec19370
Revises: b7c8d9e0f1a2
Create Date: 2026-05-21 11:01:56.677003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7da60ec19370"
down_revision: Union[str, None] = "b7c8d9e0f1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "errors",
        "description",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.String(length=16384),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "errors",
        "description",
        existing_type=sa.String(length=16384),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
