"""catalog tables

Revision ID: 1b8cdd5facec
Revises: f6fc05b42439
Create Date: 2026-02-08 17:53:15.610172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b8cdd5facec"
down_revision: Union[str, None] = "f6fc05b42439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    op.create_table(
        "reference_items",
        sa.Column(
            "type",
            sa.Enum("FAULT", "TIP", "GLOSSARY", "FAQ", name="referencetype"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("keywords", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_items")),
    )
    op.create_table(
        "certificates",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("certificate_number", sa.String(), nullable=False),
        sa.Column("issue_date", sa.DateTime(), nullable=False),
        sa.Column("pdf_url", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_certificates_course_id_courses"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_certificates_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint(
            "certificate_number",
            name=op.f("uq_certificates_certificate_number"),
        ),
    )
    op.create_table(
        "course_blocks",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("video_url", sa.String(), nullable=True),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_blocks_course_id_courses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_blocks")),
    )
    op.create_table(
        "test_questions",
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum("SINGLE", "MULTI", "OPNE", name="questiontype"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["course_blocks.id"],
            name=op.f("fk_test_questions_block_id_course_blocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_questions")),
    )
    op.create_table(
        "test_submissions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("inspection_comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["course_blocks.id"],
            name=op.f("fk_test_submissions_block_id_course_blocks"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_test_submissions_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_submissions")),
    )
    op.create_table(
        "user_block_progresss",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("is_unlocked", sa.Boolean(), nullable=False),
        sa.Column("video_watched", sa.Boolean(), nullable=False),
        sa.Column("test_passed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["course_blocks.id"],
            name=op.f("fk_user_block_progresss_block_id_course_blocks"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_block_progresss_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_block_progresss")),
    )
    op.create_table(
        "question_options",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["test_questions.id"],
            name=op.f("fk_question_options_question_id_test_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_options")),
    )
    op.create_table(
        "user_answers",
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("selected_option_id", sa.UUID(), nullable=True),
        sa.Column("text_answer", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["test_questions.id"],
            name=op.f("fk_user_answers_question_id_test_questions"),
        ),
        sa.ForeignKeyConstraint(
            ["selected_option_id"],
            ["question_options.id"],
            name=op.f("fk_user_answers_selected_option_id_question_options"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["test_submissions.id"],
            name=op.f("fk_user_answers_submission_id_test_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_answers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_answers")
    op.drop_table("question_options")
    op.drop_table("user_block_progresss")
    op.drop_table("test_submissions")
    op.drop_table("test_questions")
    op.drop_table("course_blocks")
    op.drop_table("certificates")
    op.drop_table("reference_items")
    op.drop_table("courses")
    # ### end Alembic commands ###
