"""add trgm indexes to term and product description

Revision ID: da941b1a4596
Revises: 2660df922906
Create Date: 2026-03-09 15:06:16.300421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da941b1a4596"
down_revision: Union[str, None] = "2660df922906"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_product_description_trgm",
        "products",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_term_description_trgm",
        "terms",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_term_title_trgm",
        "terms",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_term_title_trgm",
        table_name="terms",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_term_description_trgm",
        table_name="terms",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_product_description_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
