"""using trigramm

Revision ID: 3990a0f1e576
Revises: 429fc48bdfc1
Create Date: 2026-02-10 19:19:06.326841

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3990a0f1e576"
down_revision: Union[str, None] = "429fc48bdfc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_index(
        "idx_product_title_trgm",
        "products",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_product_title_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
