"""add_user_role

Revision ID: 5851fc267d5f
Revises: 3aa5b6ccbee9
Create Date: 2026-02-04 16:23:38.657065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5851fc267d5f"
down_revision: Union[str, None] = "3aa5b6ccbee9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Сначала создаем сам тип ENUM в базе данных
    user_role_enum = postgresql.ENUM(
        "user", "admin", "manager", "client", name="userrole"
    )
    user_role_enum.create(op.get_bind())

    # 2. Теперь добавляем колонку, которая использует этот тип
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("user", "admin", "manager", "client", name="userrole"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
