"""update

Revision ID: e852b73d339b
Revises: e48be111331f
Create Date: 2026-02-10 15:33:20.839136

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e852b73d339b"
down_revision: Union[str, None] = "e48be111331f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column(
        "search_product",
        postgresql.TSVECTOR(),
        sa.Computed(
            "to_tsvector('russian', coalesce(title, '') || ' ' || coalesce(description, '')"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
