"""refactor: replace int on uuid

Revision ID: 3d1c8f24ce89
Revises: a320c8d96f01
Create Date: 2026-03-19 14:04:00.747067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d1c8f24ce89"
down_revision: Union[str, None] = "a320c8d96f01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "search_product",
        existing_type=postgresql.TSVECTOR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "search_product",
        existing_type=postgresql.TSVECTOR(),
        nullable=True,
    )
    # ### end Alembic commands ###
