"""update table id

Revision ID: c6a74b926230
Revises: df1f06ae3d55
Create Date: 2026-02-15 22:27:55.685733

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6a74b926230"
down_revision: Union[str, None] = "df1f06ae3d55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses",
        "title",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "documentation",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "documentation",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "courses",
        "title",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
