"""update table

Revision ID: 5d40b2650241
Revises: 8ddc2e11525d
Create Date: 2026-02-10 14:36:40.230809

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5d40b2650241"
down_revision: Union[str, None] = "8ddc2e11525d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "description",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "products", "schema_connect", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "products",
        "documentation",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
    )
    op.drop_column("products", "search_product")

    # Добавляем новую с правильным вычислением
    # Важно: используем sa.text для передачи SQL-выражения генерации
    op.add_column(
        "products",
        sa.Column(
            "search_product",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('russian', title || ' ' || coalesce(description, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
    )

    # Создаем индекс
    op.create_index(
        "idx_search_product", "products", ["search_product"], postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "documentation",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "products",
        "schema_connect",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.drop_index("idx_search_product", table_name="products", postgresql_using="gin")
    op.drop_column("products", "search_product")
    op.add_column(
        "products", sa.Column("search_product", postgresql.TSVECTOR(), nullable=True)
    )
    # ### end Alembic commands ###
