"""create new table product

Revision ID: 8bb42682dc1c
Revises: e852b73d339b
Create Date: 2026-02-10 15:44:58.826081

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bb42682dc1c"
down_revision: Union[str, None] = "e852b73d339b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "products" not in inspector.get_table_names():
        op.create_table(
            "products",
            sa.Column("title", sa.String(length=256), nullable=False),
            sa.Column("description", sa.String(length=1024), nullable=False),
            sa.Column(
                "image_url",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
            ),
            sa.Column("schema_connect", sa.String(), nullable=True),
            sa.Column("documentation", sa.String(), nullable=True),
            sa.Column(
                "attributes",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
            ),
            sa.Column(
                "search_product",
                postgresql.TSVECTOR(),
                sa.Computed(
                    "to_tsvector('russian', coalesce(title,'') || ' ' || coalesce(description,''))",
                    persisted=True,
                ),
                nullable=False,
            ),
            sa.Column("id", sa.UUID(), nullable=False),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        )
        op.create_index(
            "idx_search_product",
            "products",
            ["search_product"],
            unique=False,
            postgresql_using="gin",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_search_product", table_name="products", postgresql_using="gin")
    op.drop_table("products")
    # ### end Alembic commands ###
