"""fix(database): move data type

Revision ID: 28a748f3d4ee
Revises: 0ed4a07959fc
Create Date: 2026-02-05 16:08:23.523110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28a748f3d4ee"
down_revision: Union[str, None] = "0ed4a07959fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
